<?php
/**
 * Favicons
 * 
 * Register os all favicon variations
 * The image files should be generated by the gulp favicons task, using a base PNG as source
 * 
 * Iputs: $path
 * 
 * Reference: https://www.npmjs.com/package/favicons
 * 
 * @package tri
 */
?>

<link rel="icon" href="<?= $path; ?>/favicon.ico" />